### ISSUE TITLE
fix: show all compatible versions

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-website#147]
# Issue

Currently, the only version shown for patches on the `/patches` page is the "suggested" for each patch. This hides the important information of the patches other compatibilities to versions

# Solution

How all versions that patches are compatible with.

# Additional context

- Since the list can be quite big, collapse the list and show the suggested only. 
- When uncollapsing, uncollapse all the patches list of compatible versions, not just one, because the user's intention is likely to see them all. When collapsing again, hide them all again and show the suggested only.
- It might be favourable to index versions for search as well as add list filters for them

**Comment by Ushie** [comment]
Do you imagine it to look like this? 
![image](https://github.com/ReVanced/revanced-website/assets/79272171/5df8e1db-3665-49eb-8e06-4639557d816f)
or what do you exactly envision

**Comment by oSumAtrIX** [comment]
Every version has a chip. The intepretation of these chips are "tags".

**Comment by PalmDevs** [comment]
> Do you imagine it to look like this? 
> ![image](https://github.com/ReVanced/revanced-website/assets/79272171/5df8e1db-3665-49eb-8e06-4639557d816f)
> or what do you exactly envision

This is definitely better than separate chips. For one, it includes all the information with the same hierarchy in the exact same place, and for two, it doesn't waste too much space like multiple chips.

**Comment by oSumAtrIX** [comment]
> For one, it includes all the information with the same hierarchy in the exact same place, and for two, it doesn't waste too much space like multiple chips.

I disagree.

>  For one, it includes all the information with the same hierarchy in the exact same place

So do chips with a version in each chip

> , it doesn't waste too much space like multiple chips.

It wastes as much space as separate chips minus the padding. This is negligible.

In addition to that, readability drastically decreases: 
![image](https://github.com/ReVanced/revanced-website/assets/13122796/d1de82ed-9c03-4c1b-ae35-ac184cdfd82d)

In addition to that, functionality drastically decreases:
With separate chips, you can click on a chip, which will filter the patches list for that version. This way an interaction is added to the chip purposefully.

**Comment by Ushie** [comment]
> With separate chips, you can click on a chip, which will filter the patches list for that version. This way an interaction is added to the chip purposefully.

Would that not require changing the behavior of the package chip to do the same thing? because it's odd to use version chips for filter and then use the package name chip to link to the application's page

**Comment by PalmDevs** [comment]
I'd disagree upon using multiple chips. Firstly, using multiple chips can waste a ton of space and create layout shifts when the list (of chips) is expanded/collapsed. Secondly, as the above comment suggests, the versions have the same hierarchy, but when using multiple chips, it makes it look like the package name and the versions also do have the same hierarchy which isn't the case. Thirdly, there are better alternatives that use the intended component (list dialog) to display the content accordingly.

My suggestion would be to have 2 chips, one that shows the suggested/recommended version and the other opens a list dialog which shows the full list of supported versions. The filter option can very easily be placed below the search bar, similar to the package name filter option we already have. This would open a list dialog with **checkboxes**, so the user can filter multiple versions at the same time, likewise with chips.

**Comment by oSumAtrIX** [comment]
> Would that not require changing the behavior of the package chip to do the same thing?

Yes, that is fine.

**Comment by Ushie** [comment]
> Yes, that is fine.

How do we link to the package in that case?

**Comment by oSumAtrIX** [comment]
>  Firstly, using multiple chips can waste a ton of space and create layout shifts when the list (of chips) is expanded/collapsed.

I have already explained this [here](https://github.com/ReVanced/revanced-website/issues/147#issuecomment-1646618720):

> It wastes as much space as separate chips minus the padding. This is negligible.

> but when using multiple chips, it makes it look like the package name and the versions also do have the same hierarchy which isn't the case.

They technically do. The package name is accompanied by a list of versions that the patch is compatible with. What can become a problem is, that if the patch is compatible with multiple packages, the versions may be different for the packages. Your proposed solution above does not solve this problem.

>  intended component (list dialog) 
...
> My suggestion would be to have 2 chips, one that shows the suggested/recommended version and the other opens a list dialog which shows the full list of supported versions.

This will break UX. I have mentioned this originally [here](https://github.com/ReVanced/revanced-website/issues/147#issue-1816786494):

> When uncollapsing, uncollapse all the patches list of compatible versions, not just one, because the user's intention is likely to see them all. When collapsing again, hide them all again and show the suggested only.


>  The filter option can very easily be placed below the search bar, similar to the package name filter option we already have. This would open a list dialog with checkboxes, so the user can filter multiple versions at the same time, likewise with chips.

Search filters are an unrelated problem to this issue and thus offtopic.

**Comment by oSumAtrIX** [comment]
> > Yes, that is fine.
> 
> How do we link to the package in that case?

Currently, the page supports a filter like this: 
![image](https://github.com/ReVanced/revanced-website/assets/13122796/4de9799d-eed9-4f0a-962f-2533b81bb293)

By clicking on the package chip, the same action can be dispatched when clicking on the existing list. Offtopic to this issue though which is why this should not be further discussed.

**Comment by PalmDevs** [comment]
> > > Yes, that is fine.
> > 
> > How do we link to the package in that case?
> 
> Currently, the page supports a filter like this: 
> ![image](https://github.com/ReVanced/revanced-website/assets/13122796/4de9799d-eed9-4f0a-962f-2533b81bb293)
> 
> By clicking on the package chip, the same action can be dispatched when clicking on the existing list. Offtopic to this issue though which is why this should not be further discussed.

It looks different on mobile.
![image](https://media.discordapp.net/attachments/952987428786941952/1132346793447932115/Screenshot_20230722_232036_Firefox.jpg)

**Comment by oSumAtrIX** [comment]
> It looks different on mobile.

That is not a problem. When you click on it, it starts filtering. If the package list is shown or not does not matter. Once again, this is offtopic.

**Comment by PalmDevs** [comment]
>    I have already explained this [here](https://github.com/ReVanced/revanced-website/issues/147#issuecomment-1646618720):
> 
>    > It wastes as much space as separate chips minus the padding. This is negligible.
> 
It still wastes this space for absolutely no reason. I don't see why we should use separate chips. Layout shifts can also happen using your solution, while it doesn't on mine and readability can simply be fixed by my proposed solution, which is a list dialog.

>    They technically do. The package name is accompanied by a list of versions that the patch is compatible with. What can become a problem is, that if the patch is compatible with multiple packages, the versions may be different for the packages. Your proposed solution above does not solve this problem.
While this may somewhat be true, you do not display the list of chips in a manner that may make the user think **a specific supported version** has the same hierarchy as the supported package name. You may however, display it in a way that **a list of versions** has the same hierarchy as the supported package name.


>    This will break UX. I have mentioned this originally [here](https://github.com/ReVanced/revanced-website/issues/147#issue-1816786494):
> 
>    > When uncollapsing, uncollapse all the patches list of compatible versions, **not just one**, because **the user's intention is likely to see them all**. When collapsing again, hide them all again and show the suggested only.
> 
If the user's intention is likely to see them all, the list dialog will also serve that purpose. Tapping the chip beside the suggested/recommended version opens a dialog with the full list of supported versions in my proposal.

>    Search filters are an unrelated problem to this issue and thus offtopic. 
You've mentioned about indexing via version in your issue.

**Comment by PalmDevs** [comment]
>    They technically do. The package name is accompanied by a list of versions that the patch is compatible with. What can become a problem is, that if the patch is compatible with multiple packages, the versions may be different for the packages. Your proposed solution above does not solve this problem.

How does your problem solve this issue?

**Comment by oSumAtrIX** [comment]
- > It still wastes this space for absolutely no reason. 

   That is incorrect. As I said, the additional space it "wastes" is just the negligible paddings. Additionally "for absolutely no reason is wrong" because of what I said earlier [here](https://github.com/ReVanced/revanced-website/issues/147#issuecomment-1646618720):
   > In addition to that, functionality drastically decreases.

- > If the user's intention is likely to see them all, the list dialog will also serve that purpose. Tapping the chip beside the suggested/recommended version opens a dialog with the full list of supported versions in my proposal.

   You have misunderstood what I meant. I meant that the user wants to see the compatibility of ALL patches. When they uncollapse the version chips, they will look at the patches and check which ones support what versions. If you'd use a dialog UX is drastically impaired because they would have to iterate through every patch, click on the chip to open the dialog, then close it and move to the next patch. This destroys the intended purpose of getting an overview of the patches. Additionally functionality remains impaired as described [here](https://github.com/ReVanced/revanced-website/issues/147#issuecomment-1646618720):
   > In addition to that, functionality drastically decreases.

-   > You've mentioned about indexing via version in this issue's opening comment.

   Yes, this is for the version chips, not the packages.

**Comment by oSumAtrIX** [comment]
> How does your solution solve this issue?

It does not, nor does it create the issue. The issue persists currently because the suggested version does not necessarily apply to all packages. I can have a patch that supports pkg A with version X and pkg B with version Y but the site would show pkg A and B but version X as suggested only. Offtopic and an issue should be opened or discussed later since this issue does not create nor solve this issue.

**Comment by PalmDevs** [comment]
>    That is incorrect. As I said, the additional space it "wastes" is just the negligible padding (that are even compensating your separated list that would add spacing anyway). Additionally "for absolutely no reason is wrong" because of what I said earlier [here](https://github.com/ReVanced/revanced-website/issues/147#issuecomment-1646618720):
>    > In addition to that, functionality drastically decreases.

Except the spacing makes up for the readability and doesn't allow layout shifts since the dialog's position remains absolute and doesn't touch the elements below it whatsoever. The only issue with your current solution is it causes content shifts and displays the supported versions in a manner that makes the user thinks a specific version has the same hierarchy as the supported package name which isn't the case.

>    You have misunderstood what I meant. I meant that the user wants to see the compatibility of ALL patches. When they uncollapse the version chips, they will look at the patches and check which ones support what versions. If you'd use a dialog UX is drastically impaired because they would have to iterate through every patch, click on the chip to open the dialog, then close it and move to the next patch. This destroys the intended purpose of getting an overview of the patches. Additionally functionality remains impaired as described [here](https://github.com/ReVanced/revanced-website/issues/147#issuecomment-1646618720):
>    > In addition to that, functionality drastically decreases.
> 

The user can still view one at a time, and even if the web page could display multiple lists at a time, it wouldn't change the fact that the page can display at most about 10 cards on most devices. Not counting the layout shifts that may hide another card's chips themselves.

If the user wants to compare between versions, they can simply use a filter and check if the patch exists in the list or not.

Hiding full details under a tap doesn't mean you're restricting someone from getting an overview of any information in this case. If you want to get an overview of patches, you'd usually want to view just the suggested version, not the full list. 

>    Yes, this is for the version chips, not the packages.

You misunderstood me at this part. I said:
> similar to the package name's filter

meaning I'd place the version filter chip beside the package name filter chip (which is in the screenshot I replied with)

**Comment by oSumAtrIX** [comment]
- > Except the spacing makes up for the readability and doesn't allow layout shifts since the dialog's position remains absolute and doesn't touch the elements below it whatsoever.

   I don't know when this content shift is even a problem. Just because it adds more lines doesn't mean we should avoid it at all costs. Your dialogue would massively decrease UX as you'd need to open and close dialogues all the time to see versions of patches which is worse by a magnitude than a minimal increase of the height. Therefore:

   > The only issue with your current solution is it causes content shifts 

   It is less of a problem (if any) than showing dialogues. Grouping the versions does not improve this at all. It may decrease width 
by a little amount but, again, cause readability issues.

- > The only issue with your current solution [...] the user thinks a specific version has the same hierarchy as the supported package name which isn't the case.

   No, this is not a problem caused by my solution and neither is it solved with yours. See [this](https://github.com/ReVanced/revanced-website/issues/147#issuecomment-1646626049).

- > The user can still view one at a time

   This breaks UX. As explained above:
   > Your dialogue would massively decrease UX as you'd need to open and close dialogues all the time to see versions of patches which is worse by a magnitude than a minimal increase of the height

- > If the user wants to compare between versions, they can use a filter and check if the patch exists in the list or not.

   And what if they want to see an overview of all patches and their supported version? Showing the suggested only is not an option as it distorts information implying that it is the only version the patch supports. Showing a dialogue causes UX issue mentioned above.

- > If you want to get an overview of patches, you'd usually want to view just the suggested version, not the full list.

   If this is what you want to see, then collapse it (default). If you want to see the compatibilities of the patches, uncollapse it. 

- > beside the package name filter chip

   This does not solve the issue. Chips are unordered lists. You are trying to jam the semantics of ordered lists by displaying the version next to the package name, failing to respect hierarchy. Correct hierarchy would be, that the chip of the package name includes the versions. Chip lists are unordered therefore abusing it by showing the versions chips next to the package should not happen.

**Comment by oSumAtrIX** [comment]
Here are examples:

![image](https://github.com/ReVanced/revanced-website/assets/13122796/d22d9e8a-ffa4-46bc-97c7-0cd4b59154cb)

![image](https://github.com/ReVanced/revanced-website/assets/13122796/6cf5e064-41c3-4cec-9728-07352b1dac00)

**Comment by PalmDevs** [comment]
> - > The only issue with your current solution [...] the user thinks a specific version has the same hierarchy as the supported package name which isn't the case.
> 
>    No, this is not a problem caused by my solution and neither is it solved with yours. See [this](https://github.com/ReVanced/revanced-website/issues/147#issuecomment-1646626049).

It **is almost** solved by mine, while yours just ignores it completely. It is a problem caused by your solution, chips are unordered lists. You'd expect them to show items in the same hierarchy. If there are different hierarchies, you nest the list, like so:

- <supported_package_name>
- **Supported versions** (this is the part you missed)
  - <supported_versions[0]>
  - <supported_versions[1]>
  - ...

>    This does not solve the issue. Chips are unordered lists. You are trying to jam the semantics of ordered lists by displaying the version next to the package name, failing to respect hierarchy. The correct hierarchy would be, that the chip of the package name includes the versions. Chip lists are unordered; therefore, abusing them by showing the versions chips next to the package should not happen. 

You are definitely not understanding something. This is about indexing and filtering. See the screenshot I provided again and re-read the sentence.

**Comment by oSumAtrIX** [comment]
- > It is almost solved by mine

   Elaborate? As I said [here](https://github.com/ReVanced/revanced-website/issues/147#issuecomment-1646626049):

   > I can have a patch that supports pkg A with version X and pkg B with version Y but the site would show pkg A and B but version X as suggested only.

Your solution does not solve it at all.

- >  It is a problem caused by your solution,

   No, it is not. As I have previously said [here](https://github.com/ReVanced/revanced-website/issues/147#issuecomment-1646626049):
   > The issue persists **>>currently<<** because the suggested version does not necessarily apply to all packages. I can have a patch that supports pkg A with version X and pkg B with version Y but the site would show pkg A and B but version X as suggested only. 

   You have said this previously:
   ![image](https://github.com/ReVanced/revanced-website/assets/13122796/989d5013-681d-4d73-a7e4-1c72f3313405)

   Whereas the problem is outlined above is __not__ solved the way you have mentioned previously. Repeating:
   >  I can have a patch that supports pkg A with version X and pkg B with version Y but the site would show pkg A and B but version X as suggested only. 


- > not understanding something

   Care to explain what?

   > This is about indexing and filtering

   No, this issue is not about indexing or filtering. The title `fix: show all compatible versions` doesn't even remotely relate to it. Repeating the description of my issue:
   > Currently, the only version shown for patches on the /patches page is the "suggested" for each patch. This hides the important information of the patches other compatibilities to versions

   Indexing or filtering has nothing to do this.

**Comment by oSumAtrIX** [comment]
Keep in mind a dialog is an alternative to your supposed solution that has already been discussed to worsen UX and functionality drastically. above, whereas my solution in contrast to yours brings you:

- [Better readability](https://github.com/ReVanced/revanced-website/issues/147#issuecomment-1646649811) (Not crammed like the comma separated list)
- Additional [functionality](https://github.com/ReVanced/revanced-website/issues/147#issuecomment-1646625804)
- Convenient [UX](https://github.com/ReVanced/revanced-website/issues/147#issuecomment-1646623229): Chip click action
- Minimalistic UI by default (collapsed) but still complete information (uncollapsed)

So far, your arguments add up to:

- "More" lines due to wrapping (unsolved by your comma-separated list) /content shift by a little amount to the bottom (How is this an issue to begin with?)
- Wrong Semantics/Hirarchy (Which is neither caused by my suggestion nor solved by your solution and also currently present)

Whereas your solution:

- Decreases readability as seen [here](https://github.com/ReVanced/revanced-website/issues/147#issuecomment-1646649811) (Not crammed like the comma separated list)
- Only reduces width by a little negligible amount (and thus impairs UX as explained in the point above) thus still causes content shift (which so far I don't see how is a problem, the screen doesn't move)
- Fails to provide additional functionality when clicking on the chip (Such as the convenient way to filter for a version when clicking on a chip, because you group them)

**Comment by Ushie** [comment]
One issue that surfaced with the solution of this, is the fact that the version chips displayed are only for the **first** package in the supported packages, as patches may support multiple packages, the supported versions of the following packages aren't displayed in any form

**Comment by oSumAtrIX** [comment]
This issue is currently present and not introduced by #152. Refer to [this](https://github.com/ReVanced/revanced-website/issues/147#issuecomment-1646626049) explanation.

**Comment by Ushie** [comment]
In that case, I'll merge #152
